version: '2'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      HOST: http://34.95.34.5
      TOKEN: Um9aQilWFM
      TICKETS: 1
      T_MAX: 50
      T_MIN: 20
      DATABASE: sqlite:///C:\\dblabo.dbsqlite:///C:\\dblabo.db