name: 3. Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKER_PWD}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : Connexion docker
      run: docker login -u $USERNAME -p $PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag latest
    - name: Tag Image
      run : docker tag latest $USERNAME/oxygen-cs-grp2-eq9:latest
    - name: Push the image
      run: docker push $USERNAME/oxygen-cs-grp2-eq9:latest
