name: 3. Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKER_PWD}}
jobs:

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : Connexion docker
      run: docker login -u $USERNAME -p $PASSWORD
    - name : Creation tag temps
      id : date
      run: echo "DATE=$(date +%Y%m%d%H%M%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $USERNAME/oxygen-cs-grp2-eq9:$DATE --tag $USERNAME/oxygen-cs-grp2-eq9:latest
    - name: Push the image
      run: docker push $USERNAME/oxygen-cs-grp2-eq9 --all-tags
