on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/jobs/test
      env:
        HOST: "GITHUB"
        TOKEN: "YES"
        TICKETS: "100"
        T_MAX: "100"
        T_MIN: "100"
        DATABASE: "DBENV"

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/jobs/black

  build:
    needs: [test, black]
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/jobs/docker
      env:
        USERNAME: ${{secrets.DOCKER_USERNAME}}
        PASSWORD: ${{secrets.DOCKER_PWD}}
